### ISSUE TITLE
Updating PhantomJS

### ISSUE THREAD

**Issue by atduarte** [Muscula/html2pdf.it#11]
PhantomJS version in this repo is old. They recently updated it and, for example, page-break-inside property is fixed. And this fix would be extremely relevant.

https://github.com/ariya/phantomjs/issues/10638

Problem example: http://www.html2pdf.it/?url=https%3A%2F%2Fdl.dropboxusercontent.com%2Fu%2F84797%2Fa.html&download=false&format=A4&downloadToken=1400699487140&orientation=portrait&margin=1cm

**Comment by Muscula** [comment]
fixed in https://github.com/Muscula/html2pdf.it/commit/00481222f52e9330f25e0d328c30f59b6bdfc390
