### ISSUE TITLE
Page too big

### ISSUE THREAD

**Issue by zimt28** [Muscula/html2pdf.it#24]
Since you've updated html2pdf to 1.5, a screen which content fitted one page before, now takes one and a half pages. Everything just got bigger. Is there a way to get the same results as before?

**Comment by zimt28** [comment]
I've now started an instance of 1.4.2 on my own servers but this can't be a solution :)

**Comment by Muscula** [comment]
There is a `zoom` you can set somewhere in phantom, pull requests welcome.
